# Client container (React)
FROM node:18-alpine as build
WORKDIR /app/client

COPY client/package*.json ./
RUN npm ci

COPY client/ ./
RUN npm run build

FROM nginx:1.25-alpine
# Copy build
COPY --from=build /app/client/build /usr/share/nginx/html
# Copy nginx configuration
COPY client/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80