apiVersion: apps/v1
kind: Deployment
metadata:
  name: syncscribe-server
  namespace: syncscribe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: syncscribe-server
  template:
    metadata:
      labels:
        app: syncscribe-server
    spec:
      containers:
        - name: server
          image: us.gcr.io/meeting-trans-443019/syncscribe-server:04fe522-1755414309
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5002
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "5002"
            - name: DEEPGRAM_API_KEY
              valueFrom:
                secretKeyRef:
                  name: syncscribe-secrets
                  key: deepgram_api_key
          readinessProbe:
            httpGet:
              path: /healthz
              port: 5002
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 5002
            initialDelaySeconds: 10
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: syncscribe-server
  namespace: syncscribe
spec:
  selector:
    app: syncscribe-server
  ports:
    - name: http
      port: 5002
      targetPort: 5002