name: SyncScribe Cluster Control

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Make target to run"
        required: true
        type: choice
        options:
          - online-all
          - offline-all
        default: online-all

permissions:
  contents: read
  id-token: write

env:
  # Set via GitHub Repository Variables
  GCP_PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
  GKE_CLUSTER: ${{ vars.GKE_CLUSTER }}
  GKE_ZONE: ${{ vars.GKE_ZONE }}
  K8S_NAMESPACE: syncscribe
  USE_GKE_GCLOUD_AUTH_PLUGIN: "True"

jobs:
  control:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Authenticate to Google Cloud via Workload Identity Federation
      - name: Authenticate to Google Cloud (WIF)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_WIF_SERVICE_ACCOUNT }}
          access_token_lifetime: 3600s
          access_token_scopes: https://www.googleapis.com/auth/cloud-platform

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
          project_id: ${{ env.GCP_PROJECT_ID }}

      - name: Verify cluster access
        run: |
          kubectl version --client
          kubectl get ns
          kubectl -n "$K8S_NAMESPACE" get deploy || true

      - name: Determine action
        id: decide
        run: |
          if [ -z "${{ inputs.action }}" ]; then
            echo "target=online-all" >> "$GITHUB_OUTPUT"
          else
            echo "target=${{ inputs.action }}" >> "$GITHUB_OUTPUT"
          fi

      - name: Run make target
        run: |
          echo "Running: make ${{ steps.decide.outputs.target }}"
          make ${{ steps.decide.outputs.target }}

      - name: Show resources
        if: always()
        run: |
          kubectl -n "$K8S_NAMESPACE" get deploy,svc,ingress,pods -o wide || true

      - name: Show external endpoints
        if: always()
        run: |
          echo "Exposing services"
          echo "Name               Type            Endpoints"
          echo "-------------------------------------------------------"
          # Ingress endpoint (IP or hostname)
          INGRESS_ADDR=$(kubectl -n "$K8S_NAMESPACE" get ingress syncscribe-client -o jsonpath='{.status.loadBalancer.ingress[0].ip}' 2>/dev/null || true)
          if [ -z "$INGRESS_ADDR" ]; then
            INGRESS_ADDR=$(kubectl -n "$K8S_NAMESPACE" get ingress syncscribe-client -o jsonpath='{.status.loadBalancer.ingress[0].hostname}' 2>/dev/null || true)
          fi
          if [ -n "$INGRESS_ADDR" ]; then
            echo "syncscribe-client  Ingress         ${INGRESS_ADDR}/*"
          else
            echo "syncscribe-client  Ingress         (pending)"
          fi
          # LoadBalancer Service endpoint
          LB_IP=$(kubectl -n "$K8S_NAMESPACE" get svc syncscribe-client -o jsonpath='{.status.loadBalancer.ingress[0].ip}' 2>/dev/null || true)
          if [ -z "$LB_IP" ]; then
            LB_IP=$(kubectl -n "$K8S_NAMESPACE" get svc syncscribe-client -o jsonpath='{.status.loadBalancer.ingress[0].hostname}' 2>/dev/null || true)
          fi
          LB_PORT=$(kubectl -n "$K8S_NAMESPACE" get svc syncscribe-client -o jsonpath='{.spec.ports[0].port}' 2>/dev/null || echo 80)
          if [ -n "$LB_IP" ]; then
            echo "syncscribe-client  Load balancer   ${LB_IP}:${LB_PORT}"
            echo "Browser URL: http://${LB_IP}/"
          else
            echo "syncscribe-client  Load balancer   (pending)"
          fi

